name: Build and Push Only

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: salimmwatsefu/yadi

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v2

      # Login to GitHub Container Registry
      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Frontend (Baking in env vars from Doppler)
      - name: Build and Push Frontend
        run: |
          doppler secrets download --no-file --format env --token ${{ secrets.DOPPLER_TOKEN }} > ./ticketsafi-web/.env
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest ./ticketsafi-web
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest

      # Build Backend
      - name: Build and Push Backend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest ./ticketsafi-backend
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest